### ISSUE TITLE
Bug in Tilemap

### ISSUE THREAD

**Issue by sbmrgd** [pokitto/PokittoLib#138]
Currently Tilemap cannot be used by a screen mode that is not TASMODE, one gets an undefined reference to SDL_RenderCopySolid.
The reason for this:
in Tilemap.hpp we have: 
```
#if PROJ_SCREENMODE == TASMODE
...
#else

void SDL_RenderCopySolid( const uint8_t *data, uint32_t width, uint32_t height, int32_t x, int32_t y );
...
```
while in Tilemap.cpp we have:
```
#ifndef TASMODE

void SDL_RenderCopySolid( const uint8_t *data, uint32_t width, uint32_t height, int32_t x, int32_t y )
```
if we change the `#ifndef TASMODE` to `#if PROJ_SCREENMODE != TASMODE`, then it runs.

**Comment by pokitto** [comment]
Fixed
