### ISSUE TITLE
typo in include

### ISSUE THREAD

**Issue by dromer** [pokitto/PokittoLib#17]
https://github.com/pokitto/PokittoLib/blob/08e28c657a0f1d74549d4bdeba717995a5e8765c/Pokitto/POKITTO_LIBS/ImageFormat/BmpImage.cpp#L54

Should be ```PokittoDisplay.h```

**Comment by pokitto** [comment]
Thanks!

**Comment by pokitto** [comment]
@haviital Could you fix that please? Its on your branch, I'd like you to maintain it.
