### ISSUE TITLE
initRandom is empty in hardware

### ISSUE THREAD

**Issue by Pharap** [pokitto/PokittoLib#26]
The hardware version of `initRandom` is empty:

https://github.com/pokitto/PokittoLib/blob/54c64c68bd5822acd9adda897126bbf307f8da4f/Pokitto/POKITTO_HW/PokittoHW.cpp#L49

Is there something we can do to fill it with entropy?
Is there a hardware timer or a permenantly unconnected pin that can be sampled?

**Comment by pokitto** [comment]
initRandom now uses battery level and time(NULL) (=seconds since 1974) to initialize
