### ISSUE TITLE
Remove dead FileIO_HW.cpp code

### ISSUE THREAD

**Issue by Pharap** [pokitto/PokittoLib#50]
This code is aparently 'dead' and needs removing.

https://github.com/pokitto/PokittoLib/blob/92ecccf76a8b32aa634703d052dc8fbcbddce2aa/Pokitto/POKITTO_LIBS/FileIO/FileIO_HW.cpp

**Comment by pokitto** [comment]
Will be done after I test the new merges from Felipe

**Comment by Pharap** [comment]
Getting rid of `FileIO_HW.cpp` will also eliminate issue #16 because the function complained about in the issue won't exist anymore.
