### ISSUE TITLE
Fix loader not working properly after ~80 .bin files

### ISSUE THREAD

**Issue by Pharap** [pokitto/PokittoLib#59]
There's a relevant forum post [here](https://talk.pokitto.com/t/loader-stops-working-properly-with-more-than-80-bin-files/1316).

> Hello, dont know if it is right to put this -> i have a problem, yesterda just arrived my wonderfull Pokitto with 2GB SD card. Now when i´m addigng games/programms/demos-*.bins to on the SD card existing ones and there are over 100 -*.bins and i start the loader, i cant scroll down to select the bins to start, it stuck at the first *bin.. :( is there a limit of ~100*.bins on sd-card, and than the filesystem is overloadet?

There's a video demonstrating the issue on [this post](https://talk.pokitto.com/t/loader-stops-working-properly-with-more-than-80-bin-files/1316/3),
and here's the `.mp4` video within a `.zip` in case it's deleted: [Loader80Bins.zip](https://github.com/pokitto/PokittoLib/files/2352703/Loader80Bins.zip)

**Comment by pokitto** [comment]
This was fixed in Loader v5
